### ISSUE TITLE
ValueError: Unsupported callback API version

### ISSUE THREAD

**Issue by Donboxo** [MyHomeMyData/E3onCAN#10]
Hello,

since a few days I get the error 
"ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details"
when trying to publish my e380 data to mqtt. Seems like Paho Python MQTT 2.0 is breaking something.

**Comment by Donboxo** [comment]
Update:
Deleting the git folder and cloning it again with fresh requirements.txt installation did the trick and it works again!

**Comment by MyHomeMyData** [comment]
Great to hear you could fix it. To avoid conflicts of library versions of different applications you may consider to use [Python Virtual Environment](https://gist.github.com/ryumada/c22133988fd1c22a66e4ed1b23eca233) (venv).
