### ISSUE TITLE
OpenE3datapoints.py Mismatch in ids 1690

### ISSUE THREAD

**Issue by linux24365** [MyHomeMyData/E3onCAN#6]
Hello everybody,

I have a VX3 (with Battery) connected to a Vitocal 250. and I started rpoducing some nice graphics on my power levels. I observed a mismatch in ids 1690: It looks like that the order is not correct.  On top of that power string 2 is constantly zero'ed, the measurement has moved to ids 1834.
The setup which reflects the real values is:
 1690 : O3EComplexType(17, "ElectricalEnergySystemPhotovoltaicStatus", 
                                  [O3EInt16(2, "ActivePower cumulated", scale=1.0, signed=True), O3EInt16(2, "RectivePower cumulated", scale=1.0, signed=True),
                                   O3EInt16(2, "ActivePower String 3", scale=1.0, signed=True), O3EInt16(2, "RectivePower String 3", scale=1.0, signed=True),
                                   O3EInt16(2, "ActivePower String 2", scale=1.0, signed=True), O3EInt16(2, "RectivePower String 2", scale=1.0, signed=True),
                                   O3EInt16(2, "ActivePower String 1", scale=1.0, signed=True), O3EInt16(2, "RectivePower String 1", scale=1.0, signed=True),

BTW, thanks for the work you are doing. I really like the vicare app, but when it comes to trending and recording, there is no better way. 

With best reagards,

**Comment by MyHomeMyData** [comment]
@linux24365 Danke für den Hinweis. Die Datenpunktliste basiert auf dem Projekt [open3e](https://github.com/open3e/open3e) und da kam die Diskussion zu 1690 auch mal auf, wurde aber nie geändert. Denke aber, es ist so, wie Du es schreibst. Ich schau mir das nochmal an.
Hast Du dazu eine Unterlage oder aus der Beobachtung der Messwerte geschlossen?

**Comment by M4n197** [comment]
@linux24365 Siehe https://github.com/open3e/open3e/discussions/70 und https://github.com/open3e/open3e/discussions/70#discussioncomment-8350581

- cumulated zuerst
-  String-Reihenfolge: 1, 2, 3 = C, B, A

Da ich keinen Pull-Request gestellt habe, ist das wohl untergegangen.

**Comment by MyHomeMyData** [comment]
@linux24365 @M4n197 Ich schaue mir das morgen an. Werde es dann in open3e, E3onCAN und im ioBroker-Adapter e3oncan anpassen.

**Comment by MyHomeMyData** [comment]
ID 1690 mit Version 0.3.1 entsprechend aktualisiert.

**Comment by linux24365** [comment]
> @linux24365 Danke für den Hinweis. Die Datenpunktliste basiert auf dem Projekt [open3e](https://github.com/open3e/open3e) und da kam die Diskussion zu 1690 auch mal auf, wurde aber nie geändert. Denke aber, es ist so, wie Du es schreibst. Ich schau mir das nochmal an. Hast Du dazu eine Unterlage oder aus der Beobachtung der Messwerte geschlossen?

Hallo, Vielen Dank, Ich habe seit 1 Woche eie VX3 in Betreib und wollte überprüfen was ich mir so zusammmen gesucht habe, Abgeglichen habe mittels den Werten die ich am Display der VX3 zur Verfügung hatte. ( --Old School)
